import type { NextPage } from 'next'
import Head from 'next/head'
import CollapsibleMenu from '../components/CollapsibleMenu'
import Instructions from '../components/Instructions'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-3">
        <h1 className="text-8xl text-center">Mobile Menu</h1>
        <h2 className="text-center text-6xl">Accessible Keyboard Navigation</h2>
        <Instructions />

        <CollapsibleMenu
          title="Info"
          options={[
            { href: '/our-story/', title: 'Our Story' },
            { href: '/learn/', title: 'Learn' },
            { href: '/reviews/', title: 'Reviews' }
          ]}
        />
        <CollapsibleMenu
          title="Shop"
          options={[
            { href: '/icontinence/', title: 'Incontinence' },
            { href: '/personal-care/', title: 'Personal Care' },
            { href: '/nutrition/', title: 'Nutrition' }
          ]}
        />
        <CollapsibleMenu
          title="Help"
          options={[
            { href: '/privacy/', title: 'Privacy' },
            { href: '/terms-conditions/', title: 'Terms & Conditions' },
            { href: '/sitemap/', title: 'Sitemap' }
          ]}
        />
      </main>
    </div>
  )
}

export default Home
