import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import CollapsibleMenu from '../components/CollapsibleMenu'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <CollapsibleMenu
          title="Info"
          options={[
            { href: '/our-story/', title: 'Our Story' },
            { href: '/learn/', title: 'Learn' },
            { href: '/reviews/', title: 'Reviews' }
          ]}
        />
        <CollapsibleMenu
          title="Shop"
          options={[
            { href: '/icontinence/', title: 'Incontinence' },
            { href: '/personal-care/', title: 'Personal Care' },
            { href: '/nutrition/', title: 'Nutrition' }
          ]}
        />
        <CollapsibleMenu
          title="Help"
          options={[
            { href: '/privacy/', title: 'Privacy' },
            { href: '/terms-conditions/', title: 'Terms & Conditions' },
            { href: '/sitemap/', title: 'Sitemap' }
          ]}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
